//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A4_Task1MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Book
    {
        public short id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public short year_published { get; set; }
        public Nullable<short> number_pages { get; set; }
        public string contents { get; set; }
    }
}
